apiVersion: v1
kind: Secret
metadata:
  name: repo-rabbitboy123
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/rabbitboy123/Temp-2026-Rabbitboy.git
  username: rabbitboy123
  password: YOUR_GITHUB_TOKEN_HERE
