apiVersion: v1
kind: Secret
metadata:
  name: repo-rabbitboy013
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/rabbitboy013/Temp-2026-Rabbitboy.git
  username: rabbitboy013
  password: REDACTED_TOKEN
