apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-constraints
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Chạy sau khi Controller đã sẵn sàng
spec:
  project: default
  source:
    repoURL: 'https://github.com/rabbitboy123/Temp-2026-Rabbitboy.git'
    targetRevision: main
    path: gatekeeper/constraints
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true