apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    # Kéo manifest tĩnh chính thức trực tiếp từ kho GitHub của Gatekeeper
    repoURL: 'https://github.com/open-policy-agent/gatekeeper.git'
    targetRevision: 'v3.14.0' # Hoặc bản stable bạn muốn
    path: 'deploy/gatekeeper.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true