apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2" # Giữ nguyên wave thấp để chạy đầu tiên
spec:
  project: default
  source:
    # 1. Trỏ thẳng về chính repo cá nhân của bạn
    repoURL: 'https://github.com/rabbitboy123/Temp-2026-Rabbitboy.git'
    targetRevision: main
    # 2. Đường dẫn đến thư mục chứa file gatekeeper.yaml bạn vừa paste nội dung vào
    path: gatekeeper/controller
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true