apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    # Trỏ thẳng về chính repo GitHub sạch của bạn
    repoURL: 'https://github.com/rabbitboy123/Temp-2026-Rabbitboy.git'
    targetRevision: main
    path: gatekeeper/controller # Đường dẫn đến thư mục chứa file gatekeeper.yaml vừa tạo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gatekeeper-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true